import type { AxisResult } from '../axes/types.js'
import { EMOJI } from '../axes/types.js'

export function formatMarkdown(
  repo: string,
  results: AxisResult[],
  date = new Date()
): string {
  const dateStr = date.toISOString().slice(0, 10)

  const rows = results
    .map((r) => {
      const icon = EMOJI[r.status]
      return `| ${r.name} | ${icon} ${r.score} | ${r.delta} | ${r.alert} |`
    })
    .join('\n')

  const alerts = results.filter(
    (r) => r.status === 'red' || r.status === 'yellow'
  )

  const actions =
    alerts.length > 0
      ? alerts
          .map((r, i) => `${i + 1}. **${r.name}**: ${r.alert}`)
          .join('\n')
      : '現在、優先アクションはありません。'

  return `## KPI スナップショット — ${dateStr}

> **repo**: \`${repo}\`

| 軸 | スコア | 前回比 | アラート |
|----|--------|--------|---------|
${rows}

### 推奨アクション (優先順)

${actions}

---
*Generated by [kpi-agent](https://github.com/bonsai/kpi-agent)*`
}

export function formatJson(results: AxisResult[], date = new Date()) {
  return JSON.stringify(
    { date: date.toISOString(), results },
    null,
    2
  )
}
