name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    uses: bonsai/workflow-npm-publisher/.github/workflows/publish.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
